# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Consider Python
author: "Michal Dyzma"
email: mdyzma@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog dedicated to promote python/R/Julia as "core data science" tools.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mdyzma.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-gist

exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 10

jekyll-archives:
  enabled:
    - categories
  layout: category_archives
  permalinks:
    category: /categories/:name/

google_analytics: "UA-97434888-1"
google_adsense: "ca-pub-4566255347044004"
comments: true
disqus: "md-blog"


#SEO metadata
twitter:
  username: MichalDyzma

facebook:
 app_id: 422251294815916
 publisher: mdyzma
 admins: mdyzma

logo: /assets/md-logo.png

social:
  name: Michal Dyzma
  links:
    - https://twitter.com/MichalDyzma
    - https://www.facebook.com/michal.dyzma
    - https://www.linkedin.com/in/MichalDyzma
    - https://plus.google.com/+BenBalter
    - https://github.com/benbalter
    - https://keybase.io/benbalter


# share buttons
twitter_username:     MichalDyzma
github_username:      mdyzma
linkedin_username:    MichalDyzma
google_plus_username: mdyzma
facebook_username:    michal.dyzma
